import PageHeader from '../components/PageHeader.jsx'

export default function Privacy() {
  return (
    <>
      <PageHeader
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="Resort Travel Club, Inc. DBA RTC Luxury"
      />

      <section className="mx-auto max-w-4xl px-6 py-16 text-sm leading-relaxed text-emerald-950/80 lg:px-10">
        <div className="space-y-8">
          <div>
            <p className="text-xs uppercase tracking-wide text-emerald-950/50">Effective Date: September 16, 2026</p>
            <p className="mt-3">
              This Privacy Policy describes how Resort Travel Club, Inc., doing business as RTC
              Luxury (&ldquo;RTC Luxury,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), collects, uses, and shares
              information when you visit RTCLuxury.com or purchase our advertising services.
            </p>
            <p className="mt-3">
              RTC Luxury provides one-time advertising services to timeshare and property owners.
              We do not sell timeshare memberships, and we do not collect rental payments from
              travelers.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">1. Information We Collect</h2>
            <p className="mt-3">We may collect:</p>
            <ul className="mt-3 list-disc space-y-1 pl-5">
              <li>Contact information, such as name, mailing address, email address, and phone number</li>
              <li>Property information needed to advertise an owner&rsquo;s timeshare or residence</li>
              <li>Payment information needed to process the one-time advertising fee</li>
              <li>Communications you send us, including support requests and signed agreements</li>
              <li>Limited technical information, such as IP address, browser type, device type, and pages visited</li>
            </ul>
            <p className="mt-3">
              If you pay by card, card data is processed by our payment processor. RTC Luxury does
              not store full card numbers.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">2. How We Use Information</h2>
            <p className="mt-3">We use information to:</p>
            <ul className="mt-3 list-disc space-y-1 pl-5">
              <li>Provide and manage advertising services</li>
              <li>Process payment for advertising packages</li>
              <li>Communicate about an account, listing, or support request</li>
              <li>Operate, secure, and improve the website</li>
              <li>Comply with legal, tax, and payment-processing requirements</li>
            </ul>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">3. How We Share Information</h2>
            <p className="mt-3">We do not sell personal information.</p>
            <p className="mt-3">We may share information with:</p>
            <ul className="mt-3 list-disc space-y-1 pl-5">
              <li>Payment processors and merchant banks</li>
              <li>Website hosting, email, and other service providers who help us operate the business</li>
              <li>Professional advisors, such as accountants or attorneys</li>
              <li>Authorities when required by law</li>
            </ul>
            <p className="mt-3">
              We may also forward inquiries generated by an advertising campaign to the owner who
              purchased the advertising service.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">4. Cookies and Website Data</h2>
            <p className="mt-3">
              The website may use cookies or similar tools for basic site operation and analytics.
              You can control cookies through your browser settings.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">5. Data Retention</h2>
            <p className="mt-3">
              We keep information only as long as needed to provide services, maintain business
              records, process payments, handle disputes, and meet legal requirements.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">6. Your Choices</h2>
            <p className="mt-3">
              You may request access to, correction of, or deletion of personal information we
              hold, subject to legal and recordkeeping requirements. To make a request, contact us
              using the information below.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">7. Security</h2>
            <p className="mt-3">
              We use reasonable administrative, technical, and physical safeguards to protect
              information. No website or payment process is completely secure.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">8. Children&rsquo;s Privacy</h2>
            <p className="mt-3">
              Our services are not directed to children under 13, and we do not knowingly collect
              information from children.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">9. Changes to This Policy</h2>
            <p className="mt-3">
              We may update this Privacy Policy from time to time. The effective date above will
              be revised when a change is posted.
            </p>
          </div>

          <div>
            <h2 className="font-display text-xl italic text-emerald-950">10. Contact Us</h2>
            <p className="mt-3">
              Resort Travel Club, Inc. DBA RTC Luxury
              <br />
              333 S. Garland Ave, Floor 13
              <br />
              Orlando, FL 32801
              <br />
              Phone: 877-244-1413
              <br />
              Website: RTCLuxury.com
            </p>
          </div>
        </div>
      </section>
    </>
  )
}
